### ISSUE TITLE
paper question

### ISSUE THREAD

**Issue by xiaohanghang** [Js-Mim/mss_pytorch#10]
when the mask generate,why you need denoiser,what's the mean of this hehave.if the estimated source not well?

**Comment by Js-Mim** [comment]
The task of the "denoiser" is to fix the small details that the "masker" missed. Two things that we have noticed, given some test data, is that the "denoiser" gets rid of some small interference from other music sources, and recovers some of the lost energy from the "masker".

**Comment by xiaohanghang** [comment]
thank you！！！！
