### ISSUE TITLE
How long does it cost to train DSD100 data set using a single GPU, like geforce 1080ti?

### ISSUE THREAD

**Issue by youngsuenXMLY** [Js-Mim/mss_pytorch#11]
I run this python training demo with DSD100 data set, and I found it very slow on a geforce 1080ti GPU. Is there any way to speed up the training process?

**Comment by Js-Mim** [comment]
Hi @youngsuenXMLY,

from what i recall, on a TitanX it took 3 to 4 days for around 120 multi-tracks (DSD100 plus MedleybdB stems). If i am not mistaken the architecture of the GTX 1080Ti (not the mobile one!) is newer and in some of my experiments i could get a small boost. 

For the training procedure, there are two bottlenecks:
1) The STFT computation for a small number of wav files during training
2) The recurrent inference algorithm

For the first one, you could simply pre-compute the STFT for the dataset and then simply feed it at training. An alternative, is to implement the STFT analysis in pytorch.
These two options should give you a significant boost.

As for the second bottleneck, you could:
a) Decrease the number of iterations in the recurrent inference (both training and testing)
b) Replace the recurrent inference algorithm by a sparsity promoting regularization technique, as heuristically we observed that the recurrent inference does something similar. You can check that implementation out in the "nmr" branch of this project.
c) Use a newest model which is called MaDTwinNet: https://github.com/dr-costas/mad-twinnet . It is a regularization technique for the current method.
