### ISSUE TITLE
How should I adjust the parameters?

### ISSUE THREAD

**Issue by suntingfeng** [Js-Mim/mss_pytorch#14]
Hi,
I have a question. I use your test.wav to test the effect very well, the BGM basically disappears.
But I use Chinese songs for testing and the effect is very poor.
Does it support Chinese songs? Or how should I adjust the parameters?
Thank you!

**Comment by Js-Mim** [comment]
Hi!
Thank you very much for your comment. Unfortunately, we trained and tested our model only on Western music. I cannot really judge the effect on Chinese songs, but i would not expect the results to be very good.  Do you have Chinese multi-tracks that could be used for "fine-tuning" the model?

**Comment by suntingfeng** [comment]
Thank you very much!
I am sorry that I have no Chinese multi-tracks yet . If I have it later, consult with you again.

**Comment by Js-Mim** [comment]
> Thank you very much!
> I am sorry that I have no Chinese multi-tracks yet . If I have it later, consult with you again.
@suntingfeng 
Just for your information, a newer study that uses semi-supervised learning and synthetic mixtures can be found in: https://arxiv.org/pdf/1812.06087.pdf. An idea could be to fine-tune the current model using the objective presented in https://arxiv.org/pdf/1812.06087.pdf . As for synthetic data and Chinese multi-tracks you could have a look here:
https://sites.google.com/site/unvoicedsoundseparation/mir-1k
http://mac.citi.sinica.edu.tw/ikala/
