### ISSUE TITLE
Can this project be applied to ASR?

### ISSUE THREAD

**Issue by begeekmyfriend** [Js-Mim/mss_pytorch#2]
Appreciate for your brilliant jobs! I am curious about its application to ASR. When we send the output speech separated into ASR, would the useful information of the original speech signals be kept in good condition and not to be discarded in the process?

By the way, I have also found [rnnoise](https://people.xiph.org/~jm/demo/rnnoise/), a noise depression project for ASR with background music, the result it not satisfactory. In fact the audio set for my experiments is not aimed to speech with noise but background music. So would your project be helpful for my research?

**Comment by Js-Mim** [comment]
Hi @begeekmyfriend and thanks for your interest in our work!
ASR is something that i haven't really dug into. During our experiments we have experienced the opposite effect. That is, the voice signals are usually preserved but time-frequency magnitude samples that are (cor)related with the target signal are also preserved, allowing some interference. This can be regulated with the penalties introduced in our paper and/or the input spectral representation to the bi-directional GRU encoder (namely "self._alpha" parameter in our code).

Although the system was not trained with speech signals (actually the used dataset for training, a couple of speech and speech-like information is subject to a different class of instruments which we wanted to get rid off), i guess with a few and minor modifications you could adapt it to your research.
