### ISSUE TITLE
How Can I Train the Model and Fetch the Test Wave Files?

### ISSUE THREAD

**Issue by begeekmyfriend** [Js-Mim/mss_pytorch#3]
Would you like to provide a trained model or the testing wave files referred to in [nnet_helpers](https://github.com/Js-Mim/mss_pytorch/blob/master/helpers/nnet_helpers.py#L21) or some other resources? I did not find them on your site.

**Comment by Js-Mim** [comment]
We are planning to release the trained models soon.
The data  for training and testing is available here: https://sisec.inria.fr/sisec-2016/2016-professionally-produced-music-recordings/ .
The produced wave files (for the commercial mixtures, i.e. test_nnet) are available in our demo page.
