### ISSUE TITLE
Where is 'mir_eval' module?

### ISSUE THREAD

**Issue by begeekmyfriend** [Js-Mim/mss_pytorch#4]
I have downloaded the data set ran the program and an exception thrown showing as follows:
>  File "/home/leoma/mss_pytorch/helpers/nnet_helpers.py", line 8, in <module>
>  from mir_eval import separation as bss_eval
> ImportError: No module named mir_eval

I cannot find the module anywhere.

**Comment by Js-Mim** [comment]
The “mir-eval” is a package that can be found here: https://github.com/craffel/mir_eval . It’s used only for some benchmark tests between python and Matlab based evaluation of source separation. Our reported results use the Matlab based evaluation after writing into disk all the necessary “wav” files. You should check out also this package: https://github.com/faroit/dsdtools .
