### ISSUE TITLE
Help running code

### ISSUE THREAD

**Issue by cassdalton** [Js-Mim/mss_pytorch#5]
I'm trying to run the code from the repo, but I don't think I'm understanding how your're supposed to run it.  I cd into processess_scripts and run 'python ./main_script.py', but it complains that it can't find the helper module.  When I cd one directory above and run 'python processess_scripts/main_script.py', it then still complains that it can't find helpers.  If I run ipython and run the main script from the top directory then run it from the helpers directory, it complains that it cant find the tf_functions module.

How are you supposed to run the code?

**Comment by Js-Mim** [comment]
Hi,

set your current directory to mss_pytorch.
Then use: python processes_scripts/main_script.py .
This should run, assuming that you have the data and you added the corresponding paths to
helpers/nnet_helpers.py lines 21-25 .

**Comment by cassdalton** [comment]
I tried that and I get:
```
(virtualEnv) cass@cass-VirtualBox:~/ml/mss_pytorch$ python processes_scripts/main_script.py 
Traceback (most recent call last):
  File "processes_scripts/main_script.py", line 10, in <module>
    from helpers import visualize, nnet_helpers
ImportError: No module named 'helpers'
(virtualEnv) cass@cass-VirtualBox:~/ml/mss_pytorch$ 
```


Do you manually add anything to your python path?

**Comment by Js-Mim** [comment]
Oh, i see my mistake. I was running directly using "ipython", my bad!
For "python" you must add first the base directory to your PYTHONPATH.

Thanks @dr-costas !

**Comment by cassdalton** [comment]
After adding the mss_pytorch directory to the PYTHONPATH, I get:
```
(virtualEnv) cass@cass-VirtualBox:~/ml/mss_pytorch$ python processes_scripts/main_script.py 
Traceback (most recent call last):
  File "processes_scripts/main_script.py", line 10, in <module>
    from helpers import visualize, nnet_helpers
  File "/home/cass/ml/mss_pytorch/helpers/nnet_helpers.py", line 7, in <module>
    from .masking_methods import FrequencyMasking as Fm
  File "/home/cass/ml/mss_pytorch/helpers/masking_methods.py", line 7, in <module>
    from tf_methods import TimeFrequencyDecomposition as TF
ImportError: No module named 'tf_methods'

```
I have also tried  running the script in ipython, but I can't figure out how to run the script itself either.

**Comment by Js-Mim** [comment]
Could you please try the following:
export PYTHONPATH=$PYTHONPATH:/home/cass/ml/mss_pytorch
python processes_scripts/main_script.py

**Comment by begeekmyfriend** [comment]
@cassdalton 
```shell
sudo pip install dsdtools
cp processes_scripts/main_script.py .
python main_script.py
```

**Comment by cassdalton** [comment]
My PYTHONPATH was empty before I added the mss_pytorch directory to it, so appending the existing PYTHONPATH won't do any good;
I tried @begeekmyfriend 's solution of copying the main_script.py to the top level but I still get the error of not being able to import tf_methods.

**Comment by Js-Mim** [comment]
Could you please do the following:
- Make a fresh clone of the repository
- Make sure you are on the master branch (not the gh-pages)
- Your current directory is: /path/to/mss_pytorch
- While running ipython and your current directory is still:  /path/to/mss_pytorch 
  - Typing "ls helpers/" will give you the list of the necessary python scripts
  -  Typing "import  helpers.tf_methods as TF" will return you the corresponding class

**Comment by cassdalton** [comment]
so I was able to work around the tf_methods issue by referencing the module as helpers.tf_methods instead of tf_methods in the imports in both masking_methods.py and nnet_helpers.py

**Comment by Js-Mim** [comment]
Fixed in the latest commit.
