### ISSUE TITLE
How should I import qmf_realtime_class? 

### ISSUE THREAD

**Issue by begeekmyfriend** [Js-Mim/mss_pytorch#6]
In `helpers/tf_method.py` there is code as follows:
```python
try:
    from QMF import qmf_realtime_class as qrf
except ImportError:
    print('PQMF class was not found. ')
```
How should I install QMF module with pip?

**Comment by Js-Mim** [comment]
QMF is not necessary and will be removed soon.

**Comment by begeekmyfriend** [comment]
Fine I am waiting for your new version.
